#############################################################################
# Makefile for building: libtodo_list.so
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  todo_list.pro
# Template: app
# Command: C:\Development\Qt\Qt\5.7\android_armv7\bin\qmake.exe -spec android-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile todo_list.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = C:\Development\Android\android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc
CXX           = C:\Development\Android\android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++
DEFINES       = -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -Wno-psabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -DANDROID -Wa,--noexecstack -fno-builtin-memmove -g -marm -O0 -fno-omit-frame-pointer -Wall -Wno-psabi -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -Wno-psabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -DANDROID -Wa,--noexecstack -fno-builtin-memmove -std=c++11 -g -g -marm -O0 -fno-omit-frame-pointer -Wall -Wno-psabi -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -IC:\Development\Qt\Qt\5.7\android_armv7\include -IC:\Development\Qt\Qt\5.7\android_armv7\include\QtQuick -IC:\Development\Qt\Qt\5.7\android_armv7\include\QtGui -IC:\Development\Qt\Qt\5.7\android_armv7\include\QtQml -IC:\Development\Qt\Qt\5.7\android_armv7\include\QtNetwork -IC:\Development\Qt\Qt\5.7\android_armv7\include\QtCore -I. -isystem C:\Development\Android\android-ndk-r12b\sources\cxx-stl\gnu-libstdc++\4.9\include -isystem C:\Development\Android\android-ndk-r12b\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include -isystem C:\Development\Android\android-ndk-r12b\platforms\android-9\arch-arm\usr\include -IC:\Development\Qt\Qt\5.7\android_armv7\mkspecs\android-g++
QMAKE         = C:\Development\Qt\Qt\5.7\android_armv7\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
TAR           = 
COMPRESS      = 
DISTNAME      = libtodo_list.so1.0.0
DISTDIR = D:\Projects\Qt\todo_list\.tmp\libtodo_list.so1.0.0
LINK          = C:\Development\Android\android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++
LFLAGS        = --sysroot=C:\Development\Android\android-ndk-r12b/platforms/android-9/arch-arm/ -Wl,-soname,libtodo_list.so -Wl,--no-undefined -Wl,-z,noexecstack -shared
LIBS          = $(SUBLIBS) -LC:\Development\Android\android-ndk-r12b/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -LC:\Development\Android\android-ndk-r12b/platforms/android-9/arch-arm//usr/lib -LC:/Development/Qt/Qt/5.7/android_armv7/lib -lQt5Quick -Lc:/utils/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -Lc:/utils/android-ndk-r10e/platforms/android-9/arch-arm//usr/lib -LC:\Development\Qt\Qt\5.7\android_armv7/lib -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGLESv2 -lgnustl_shared -llog -lz -lm -ldl -lc -lgcc
AR            = C:\Development\Android\android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ar cqs
RANLIB        = C:\Development\Android\android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ranlib
SED           = $(QMAKE) -install sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp
OBJECTS       = main.obj \
		qrc_qml.obj
DIST          =   main.cpp
QMAKE_TARGET  = libtodo_list.so
DESTDIR       = 
TARGET        = libtodo_list.so


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: todo_list.pro C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\android-g++\qmake.conf C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\spec_pre.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\common\unix.conf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\common\linux.conf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\common\sanitize.conf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\common\gcc-base.conf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\common\gcc-base-unix.conf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\qdevice.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\device_config.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\qconfig.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dextras.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dquickextras.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3drender.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_androidextras.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_androidextras_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_charts.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_charts_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_clucene_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_core.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_core_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_datavisualization.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_datavisualization_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_gamepad.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_gamepad_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_gui.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_help.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_help_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_location.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_location_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_network.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_network_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_nfc.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_opengl.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_platformsupport_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_positioning.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_purchasing.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_purchasing_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_qml.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_quick.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_script.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_script_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_scripttools.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_scripttools_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_scxml.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_sensors.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_serialbus.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_serialbus_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_serialport.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_sql.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_svg.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_testlib.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_uitools.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_websockets.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_webview.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_widgets.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_xml.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\qt_functions.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\qt_config.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\android-g++\qmake.conf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\spec_post.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\exclusive_builds.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\default_pre.prf \
		deployment.pri \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\resolve_config.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\default_post.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\qml_debug.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\android\android.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\android\android_deployment_settings.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\warn_on.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\qt.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\resources.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\moc.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\unix\opengl.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\unix\thread.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\file_copies.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\testcase_targets.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\exceptions.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\yacc.prf \
		C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\lex.prf \
		todo_list.pro \
		qml.qrc \
		C:\Development\Qt\Qt\5.7\android_armv7\lib\libQt5Quick.prl \
		C:\Development\Qt\Qt\5.7\android_armv7\lib\libQt5Gui.prl \
		C:\Development\Qt\Qt\5.7\android_armv7\lib\libQt5Qml.prl \
		C:\Development\Qt\Qt\5.7\android_armv7\lib\libQt5Network.prl \
		C:\Development\Qt\Qt\5.7\android_armv7\lib\libQt5Core.prl
	$(QMAKE) -spec android-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile todo_list.pro
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\spec_pre.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\common\unix.conf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\common\linux.conf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\common\sanitize.conf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\common\gcc-base.conf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\common\gcc-base-unix.conf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\qdevice.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\device_config.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\qconfig.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dcore.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dextras.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dinput.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dquick.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dquickextras.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dquickextras_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3drender.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_androidextras.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_androidextras_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_charts.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_charts_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_clucene_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_concurrent.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_core.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_core_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_datavisualization.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_datavisualization_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_gamepad.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_gamepad_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_gui.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_gui_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_help.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_help_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_location.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_location_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_multimedia.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_network.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_network_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_nfc.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_opengl.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_positioning.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_printsupport.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_purchasing.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_purchasing_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_qml.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_qml_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_qmltest.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_quick.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_quick_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_script.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_script_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_scripttools.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_scxml.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_scxml_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_sensors.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_serialbus.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_serialbus_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_serialport.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_sql.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_sql_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_svg.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_svg_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_testlib.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_uitools.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_webchannel.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_websockets.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_webview.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_webview_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_widgets.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_xml.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_xml_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\modules\qt_lib_zlib_private.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\qt_functions.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\qt_config.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\android-g++\qmake.conf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\spec_post.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\exclusive_builds.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\default_pre.prf:
deployment.pri:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\resolve_config.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\default_post.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\qml_debug.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\android\android.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\android\android_deployment_settings.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\warn_on.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\qt.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\resources.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\moc.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\unix\opengl.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\unix\thread.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\file_copies.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\testcase_targets.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\exceptions.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\yacc.prf:
C:\Development\Qt\Qt\5.7\android_armv7\mkspecs\features\lex.prf:
todo_list.pro:
qml.qrc:
C:\Development\Qt\Qt\5.7\android_armv7\lib\libQt5Quick.prl:
C:\Development\Qt\Qt\5.7\android_armv7\lib\libQt5Gui.prl:
C:\Development\Qt\Qt\5.7\android_armv7\lib\libQt5Qml.prl:
C:\Development\Qt\Qt\5.7\android_armv7\lib\libQt5Network.prl:
C:\Development\Qt\Qt\5.7\android_armv7\lib\libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec android-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile todo_list.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`\$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@if not exist $(DISTDIR) mkdir $(DISTDIR) & if not exist $(DISTDIR) exit 1
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)\
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)\
	$(COPY_FILE) --parents main.cpp $(DISTDIR)\


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		C:\Development\Qt\Qt\5.7\android_armv7\bin\rcc.exe \
		colors\c600.png \
		colors\c50.png \
		colors\c800.png \
		common_skins\bottom_to_top_shadow_5.png \
		common_skins\left_to_right_shadow_5.png \
		common_skins\right_to_left_shadow_5.png \
		common_skins\top_to_bottom_shadow_10.png \
		common\ListItem.qml \
		common\ToolBar.qml \
		common\Skins.qml \
		common\TextLabel.qml \
		icons\menu_48_48.png \
		NavigationMenu.qml \
		main.qml
	C:\Development\Qt\Qt\5.7\android_armv7\bin\rcc.exe -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

####### Compile

main.obj: main.cpp C:\Development\Qt\Qt\5.7\android_armv7\include\QtGui\QGuiApplication \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtGui\qguiapplication.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qcoreapplication.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qglobal.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qconfig.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qfeatures.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qsystemdetection.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qprocessordetection.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qcompilerdetection.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qtypeinfo.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qtypetraits.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qisenum.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qsysinfo.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qlogging.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qflags.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qatomic.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qbasicatomic.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qatomic_bootstrap.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qgenericatomic.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qatomic_cxx11.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qatomic_msvc.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qglobalstatic.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qmutex.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qnumeric.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qversiontagging.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qstring.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qchar.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qbytearray.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qrefcount.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qnamespace.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qarraydata.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qstringbuilder.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qobject.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qobjectdefs.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qobjectdefs_impl.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qlist.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qalgorithms.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qiterator.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qhashfunctions.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qpair.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qbytearraylist.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qstringlist.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qregexp.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qstringmatcher.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qcoreevent.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qscopedpointer.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qmetatype.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qvarlengtharray.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qcontainerfwd.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qobject_impl.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qeventloop.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtGui\qwindowdefs.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtGui\qwindowdefs_win.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtGui\qinputmethod.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qlocale.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qvariant.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qmap.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qdebug.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qhash.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qtextstream.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qiodevice.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qvector.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qpoint.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qset.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qcontiguouscache.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qsharedpointer.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qshareddata.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qsharedpointer_impl.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qsize.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtQml\QQmlApplicationEngine \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtQml\qqmlapplicationengine.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtQml\qqmlengine.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qurl.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qurlquery.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtQml\qjsengine.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtQml\qjsvalue.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtQml\qtqmlglobal.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtQml\qqml.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtQml\qqmlprivate.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtQml\qqmlparserstatus.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtQml\qqmlpropertyvaluesource.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtQml\qqmllist.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtCore\qmetaobject.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtQml\qqmlerror.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtQml\qqmldebug.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtQml\QQmlComponent \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtQml\qqmlcomponent.h \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtQml\QQmlContext \
		C:\Development\Qt\Qt\5.7\android_armv7\include\QtQml\qqmlcontext.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.obj main.cpp

qrc_qml.obj: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.obj qrc_qml.cpp

####### Install

install_target: first FORCE
	@if not exist $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a mkdir $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a & if not exist $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a exit 1
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a\$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a\$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

